### ISSUE TITLE
module.js:478 Error: Cannot find module 'minimist'

### ISSUE THREAD

**Issue by b8n2u** [LakeYS/7DTD-Discord#114]
trying to start the bot for the first time, i get this error 

```
module.js:478
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/7dtd/7dtd-discord/index.js:7:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
Application closed with exit code 1. Restarting in 5s, press Ctrl+C to cancel.
```

**Comment by LakeYS** [comment]
Make sure you have run install.bat on Windows or `npm install` on Linux. There should be a folder named `node_modules`.

**Comment by b8n2u** [comment]
thank you it works
